apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
- name: postgres-secret
  literals:
  - postgres-username=postgres
  - postgres-password=postgres
  - postgres-host-auth-method=trust

commonLabels:
  category: database-postgres
  
